# Copyright (c) 2023 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: catie-6tron
      url-base: https://github.com/catie-aq

  defaults:
    remote: catie-6tron

  projects:
    - name: 6tron-connector
      repo-path: zephyr_6tron-connector
      revision: 5594403822b9a258d168df22dd35aefa06344668
      path: 6tron/6tron-connector
# ================== Zest Core boards ==================
    - name: zest-core-fmlr-72
      repo-path: zephyr_zest-core-fmlr-72
      revision: 46fa67b622d7faa966c9a4e99c1859f2284fb038
      path: 6tron/zest-core-fmlr-72
    - name: zest-core-nrf52832
      repo-path: zephyr_zest-core-nrf52832
      revision: 2c91fe7d363741bac3a7ff4ada7695f8675b5697
      path: 6tron/zest-core-nrf52832
    - name: zest-core-stm32g474ve
      repo-path: zephyr_zest-core-stm32g474ve
      revision: 57e0b57a257c10405328be350d0d4150532f6b16
      path: 6tron/zest-core-stm32g474ve
    - name: zest-core-stm32h753zi
      repo-path: zephyr_zest-core-stm32h753zi
      revision: 7cc92e6f71d3bad424694312df4dcdd4dbb3cd0e
      path: 6tron/zest-core-stm32h753zi
    - name: zest-core-stm32l4a6rg
      repo-path: zephyr_zest-core-stm32l4a6rg
      revision: c50c850f344d21fdcf612ac5fd96c9f15334bd50
      path: 6tron/zest-core-stm32l4a6rg
    - name: zest-core-stm32l562ve
      repo-path: zephyr_zest-core-stm32l562ve
      revision: 695c4d81e83e8e96cfcc93de79f51469855c3f35
      path: 6tron/zest-core-stm32l562ve
# ================= Integrated Devices =================
    - name: z-iaq
      repo-path: zephyr_z-iaq
      revision: 778f0a4cad56fa8f1c719d8f3381f30c36c9de22
      path: 6tron/z-iaq
    - name: z-motion
      repo-path: zephyr_z-motion
      revision: 385087b102bd032c369eff7d28bf969fe7332e81
      path: 6tron/z-motion
# ==================== Zest boards =====================
    - name: zest-interface-ethernet
      repo-path: zephyr_zest-interface-ethernet
      revision: 765c0029818806c1d7101b8a83ae57036d80744f
      path: 6tron/zest-interface-ethernet
    - name: zest-radio-gnss
      repo-path: zephyr_zest-radio-gnss
      revision: 3e583e39e8c7dc58888fdfa9ba8a44ba623bc7be
      path: 6tron/zest-radio-gnss
    - name: zest-radio-lora868
      repo-path: zephyr_zest-radio-lora868
      revision: aa9f3da891782638634d47b40b0ead3f64bd0551
      path: 6tron/zest-radio-lora868
    - name: zest-sensor-imu
      repo-path: zephyr_zest-sensor-imu
      revision: b1ff40a85fdd29af3c5140b2a82dfb96b4775124
      path: 6tron/zest-sensor-imu
    - name: zest-sensor-p-t-rh
      repo-path: zephyr_zest-sensor-p-t-rh
      revision: 51d37df1461e96700aba094f680adc9a45b969b5
      path: 6tron/zest-sensor-p-t-rh
# ====================== Drivers =======================
    - name: ams-as621x
      repo-path: zephyr_ams-as621x
      revision: 5f1202c926994dc2b9647c4938fc9c161832abf3
      path: 6tron/ams-as621x
    - name: honeywell-hpma115
      repo-path: zephyr_honeywell-hpma115
      revision: 336a914299901b46bc4ecfcb0d8e1177e6db1615
      path: 6tron/honeywell-hpma115
    - name: omron-2smpb-02e
      repo-path: zephyr_omron-2smpb-02e
      revision: a561e56135bdb0ce7c37e04bf5f707217beae5d5
      path: 6tron/omron-2smpb-02e
    - name: sensirion-scd4x
      repo-path: zephyr_sensirion-scd4x
      revision: 12ffaa8457665a7c973743d94288fdc7775e7b2a
      path: 6tron/sensirion-scd4x
    - name: te-connectivity-htu21d
      repo-path: zephyr_te-connectivity-htu21d
      revision: 570b06f9a5fe0d12a9dedf66ef06247cd5433e99
      path: 6tron/te-connectivity-htu21d
    - name: microchip-mcp3425
      repo-path: zephyr_microchip-mcp3425
      revision: cbf4e9376d2e96647233e3c05959fc6ea1ce395a
      path: 6tron/microchip-mcp3425
