# Copyright (c) 2023 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: catie-6tron
      url-base: https://github.com/catie-aq

  defaults:
    remote: catie-6tron

  projects:
    - name: 6tron_connector
      repo-path: zephyr_6tron-connector
      revision: 7796488103213b53db64830809c55ba2e34016e1
      path: 6tron/6tron_connector

    # ================== Zest_Core Boards ==================
    - name: zest_core_fmlr-72
      repo-path: zephyr_zest-core-fmlr-72
      revision: cab684c0817fe1d3c6282fcdd752a5411229d568
      path: 6tron/boards/zest_core_fmlr-72
    - name: zest_core_nrf52832
      repo-path: zephyr_zest-core-nrf52832
      revision: f3afe007ccf9860b7be3b17b6b9904e7b0c897da
      path: 6tron/boards/zest_core_nrf52832
    - name: zest_core_nrf5340
      repo-path: zephyr_zest-core-nrf5340
      revision: c8d6522aa58dea90814b048cdd51cbe9c49ad64c
      path: 6tron/boards/zest_core_nrf5340
    - name: zest_core_stm32g474ve
      repo-path: zephyr_zest-core-stm32g474ve
      revision: afdf5debdeae6c1149db698d7253b573a80a9f9e
      path: 6tron/boards/zest_core_stm32g474ve
    - name: zest_core_stm32h753zi
      repo-path: zephyr_zest-core-stm32h753zi
      revision: b90c345a85dc03f6e2d4f6306f100fc3c4d150d5
      path: 6tron/boards/zest_core_stm32h753zi
    - name: zest_core_stm32l4a6rg
      repo-path: zephyr_zest-core-stm32l4a6rg
      revision: 782620ec7b137b7c7166a8337333b094c5c4466a
      path: 6tron/boards/zest_core_stm32l4a6rg
    - name: zest_core_stm32l562ve
      repo-path: zephyr_zest-core-stm32l562ve
      revision: 3258d7b0394d7dec20a9263dd4b6c22cfcf484df
      path: 6tron/boards/zest_core_stm32l562ve

    # ================= Integrated Devices =================
    - name: z_iaq
      repo-path: zephyr_z-iaq
      revision: 972051c8dafbf4ed1027eb16ff2c086bfa6a605b
      path: 6tron/boards/z_iaq
    - name: z_motion
      repo-path: zephyr_z-motion
      revision: a90f1319ac9c84bf8eec49dcbd0c366cb165be9e
      path: 6tron/boards/z_motion

    # ==================== Zest Shields =====================
    - name: zest_adapter_click
      repo-path: zephyr_zest-adapter-click
      revision: 35e370b58ee8deb483f507003bad77d69cd0d40d
      path: 6tron/shields/zest_adapter_click
    - name: zest_interface_ethernet
      repo-path: zephyr_zest-interface-ethernet
      revision: 765c0029818806c1d7101b8a83ae57036d80744f
      path: 6tron/shields/zest_interface_ethernet
    - name: zest_interface_rs485
      repo-path: zephyr_zest-interface-rs485
      revision: 01ce3c2378d6b2fca544dea3af8d27d6ba78bd06
      path: 6tron/shields/zest_interface_rs485
    - name: zest_radio_gnss
      repo-path: zephyr_zest-radio-gnss
      revision: 3e583e39e8c7dc58888fdfa9ba8a44ba623bc7be
      path: 6tron/shields/zest_radio_gnss
    - name: zest_radio_lora868
      repo-path: zephyr_zest-radio-lora868
      revision: aa9f3da891782638634d47b40b0ead3f64bd0551
      path: 6tron/shields/zest_radio_lora868
    - name: zest_sensor_imu
      repo-path: zephyr_zest-sensor-imu
      revision: b1ff40a85fdd29af3c5140b2a82dfb96b4775124
      path: 6tron/shields/zest_sensor_imu
    - name: zest_sensor_p-t-rh
      repo-path: zephyr_zest-sensor-p-t-rh
      revision: 51d37df1461e96700aba094f680adc9a45b969b5
      path: 6tron/shields/zest_sensor_p-t-rh

    # ====================== Drivers =======================
    - name: ams_as621x
      repo-path: zephyr_ams-as621x
      revision: 096219be378848cb9a319b27095b5db6ce2f5fac
      path: 6tron/drivers/ams_as621x
    - name: honeywell_hpma115
      repo-path: zephyr_honeywell-hpma115
      revision: 415fc7e870d8e012e0f80674a5223c5d7dcde5d0
      path: 6tron/drivers/honeywell_hpma115
    - name: omron_2smpb-02e
      repo-path: zephyr_omron-2smpb-02e
      revision: 8c985b1fb7087344e883f01f94bac72e06374dfd
      path: 6tron/drivers/omron_2smpb-02e
    - name: sensirion_scd4x
      repo-path: zephyr_sensirion-scd4x
      revision: 5e263765723ac61d21c0e27f633089cc83d2bbb6
      path: 6tron/drivers/sensirion_scd4x
    - name: te-connectivity_htu21d
      repo-path: zephyr_te-connectivity-htu21d
      revision: 5614450235a9ea30cd62478a7464d2df00c257ec
      path: 6tron/drivers/te-connectivity_htu21d
    - name: microchip_mcp3425
      repo-path: zephyr_microchip-mcp3425
      revision: cb0b33cb6d17e2c9133fab3f10bb33b59f4e2c5e
      path: 6tron/drivers/microchip_mcp3425
