# Copyright (c) 2023 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: catie-6tron
      url-base: https://github.com/catie-aq

  defaults:
    remote: catie-6tron

  projects:
    - name: 6tron-connector
      repo-path: zephyr_6tron-connector
      revision: 5594403822b9a258d168df22dd35aefa06344668
      path: 6tron/6tron-connector
# ================== Zest Core boards ==================
    - name: zest-core-nrf52832
      repo-path: zephyr_zest-core-nrf52832
      revision: 2c91fe7d363741bac3a7ff4ada7695f8675b5697
      path: 6tron/zest-core-nrf52832
    - name: zest-core-stm32g474ve
      repo-path: zephyr_zest-core-stm32g474ve
      revision: 57e0b57a257c10405328be350d0d4150532f6b16
      path: 6tron/zest-core-stm32g474ve
    - name: zest-core-stm32l4a6rg
      repo-path: zephyr_zest-core-stm32l4a6rg
      revision: 5f9218a702cf9b13a97c5c2aad8b552dd1eebe58
      path: 6tron/zest-core-stm32l4a6rg
# ================= Integrated Devices =================
    - name: z-iaq
      repo-path: zephyr_z-iaq
      revision: 778f0a4cad56fa8f1c719d8f3381f30c36c9de22
      path: 6tron/z-iaq
# ==================== Zest boards =====================
    - name: zest-radio-gnss
      repo-path: zephyr_zest-radio-gnss
      revision: f2ea9a1a6c0f2171b20309aa2b42acfb02271dbc
      path: 6tron/zest-radio-gnss
    - name: zest-sensor-imu
      repo-path: zephyr_zest-sensor-imu
      revision: b1ff40a85fdd29af3c5140b2a82dfb96b4775124
      path: 6tron/zest-sensor-imu
    - name: zest-sensor-p-t-rh
      repo-path: zephyr_zest-sensor-p-t-rh
      revision: 51d37df1461e96700aba094f680adc9a45b969b5
      path: 6tron/zest-sensor-p-t-rh
# ====================== Drivers =======================
    - name: ams-as621x
      repo-path: zephyr_ams-as621x
      revision: 5f1202c926994dc2b9647c4938fc9c161832abf3
      path: 6tron/ams-as621x
    - name: honeywell-hpma115
      repo-path: zephyr_honeywell-hpma115
      revision: f49038dc384b945360ac466b0d0dcd4aa8f7500b
      path: 6tron/honeywell-hpma115
    - name: omron-2smpb-02e
      repo-path: zephyr_omron-2smpb-02e
      revision: a561e56135bdb0ce7c37e04bf5f707217beae5d5
      path: 6tron/omron-2smpb-02e
    - name: sensirion-scd4x
      repo-path: zephyr_sensirion-scd4x
      revision: 12ffaa8457665a7c973743d94288fdc7775e7b2a
      path: 6tron/sensirion-scd4x
    - name: te-connectivity-htu21d
      repo-path: zephyr_te-connectivity-htu21d
      revision: 570b06f9a5fe0d12a9dedf66ef06247cd5433e99
      path: 6tron/te-connectivity-htu21d
<<<<<<< HEAD
<<<<<<< HEAD
    - name: microchip-mcp3425
      repo-path: zephyr_microchip-mcp3425
      revision: cbf4e9376d2e96647233e3c05959fc6ea1ce395a
      path: 6tron/microchip-mcp3425
=======
    - name: zest-radio-gnss
      repo-path: zephyr_zest-radio-gnss
      revision: f2ea9a1a6c0f2171b20309aa2b42acfb02271dbc
      path: 6tron/zest-radio-gnss
>>>>>>> add zest_radio_gnss
=======
>>>>>>> move the declaration order
