# Copyright (c) 2023 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: catie-6tron
      url-base: https://github.com/catie-aq

  defaults:
    remote: catie-6tron

  projects:
    - name: 6tron-connector
      repo-path: zephyr_6tron-connector
      revision: main
      path: 6tron/6tron-connector
    - name: zest-core-stm32l4a6rg
      repo-path: zephyr_zest-core-stm32l4a6rg
      revision: master
      path: 6tron/zest-core-stm32l4a6rg
    - name: zest-sensor-imu
      repo-path: zephyr_zest-sensor-imu
      revision: master
      path: 6tron/zest-sensor-imu
    - name: zest-sensor-p-t-rh
      repo-path: zephyr_zest-sensor-p-t-rh
      revision: master
      path: 6tron/zest-sensor-p-t-rh
    - name: ams-as621x
      repo-path: zephyr_ams-as621x
      revision: master
      path: 6tron/ams-as621x
    - name: honeywell-hpma115
      repo-path: zephyr_honeywell-hpma115
      revision: main
      path: 6tron/honeywell-hpma115
