# Copyright (c) 2023 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: catie-6tron
      url-base: https://github.com/catie-aq

  defaults:
    remote: catie-6tron

  projects:
    - name: 6tron_connector
      repo-path: zephyr_6tron-connector
      revision: 7796488103213b53db64830809c55ba2e34016e1
      path: 6tron/6tron_connector

    # ================== Zest_Core Boards ==================
    - name: zest_core_fmlr-72
      repo-path: zephyr_zest-core-fmlr-72
      revision: f491466c3eccc1942e5a7aca2ba922fc9330d78f
      path: 6tron/boards/zest_core_fmlr-72
    - name: zest_core_mtxdot
      repo-path: zephyr_zest-core-mtxdot
      revision: 4fd7ffea2e02ee240c468e6169e7eae77906970c
      path: 6tron/boards/zest_core_mtxdot
    - name: zest_core_nrf52832
      repo-path: zephyr_zest-core-nrf52832
      revision: c7cab88048b51659712deac79c2680f9d919719a
      path: 6tron/boards/zest_core_nrf52832
    - name: zest_core_nrf5340
      repo-path: zephyr_zest-core-nrf5340
      revision: 40b31ebe9768c817e28358f132f3fe7c19dd4045
      path: 6tron/boards/zest_core_nrf5340
    - name: zest_core_stm32g474ve
      repo-path: zephyr_zest-core-stm32g474ve
      revision: dffdd791c525be9653b104f40cb541e3d15abaa0
      path: 6tron/boards/zest_core_stm32g474ve
    - name: zest_core_stm32h753zi
      repo-path: zephyr_zest-core-stm32h753zi
      revision: a79538ebe7437c5c28d65bf2bff05f77877ec9a8
      path: 6tron/boards/zest_core_stm32h753zi
    - name: zest_core_stm32l4a6rg
      repo-path: zephyr_zest-core-stm32l4a6rg
      revision: d0705194502134dbc39cb83038962ba14a5201cf
      path: 6tron/boards/zest_core_stm32l4a6rg
    - name: zest_core_stm32l562ve
      repo-path: zephyr_zest-core-stm32l562ve
      revision: 7f2feb3ef729f0f08e217a02731d030b977c6428
      path: 6tron/boards/zest_core_stm32l562ve

    # ================= Integrated Devices =================
    - name: z_iaq
      repo-path: zephyr_z-iaq
      revision: 4198a3f35e761fa504609f780ba36a3408e7d74a
      path: 6tron/boards/z_iaq
    - name: z_motion
      repo-path: zephyr_z-motion
      revision: bef3fc413260367756a75d2727080ed80f7df7dc
      path: 6tron/boards/z_motion

    # ==================== Zest Shields =====================
    - name: zest_adapter_click
      repo-path: zephyr_zest-adapter-click
      revision: b2f9751dcbd1a2e92e08cb6cdfbda1d351d9a64b
      path: 6tron/shields/zest_adapter_click
    - name: zest_battery_lipo
      repo-path: zephyr_zest-battery-lipo
      revision: bf11d4c2474c06692c5f609964ee9e05556902e9
      path: 6tron/shields/zest_battery_lipo
    - name: zest_display_lcd
      repo-path: zephyr_zest-display-lcd
      revision: a1bf26f9fd2aa51c42e3efc65ad1e7b60b1993d9
      path: 6tron/shields/zest_display_lcd
    - name: zest_interface_ethernet
      repo-path: zephyr_zest-interface-ethernet
      revision: b34a10f8ba6999debf3ba1eb3806b6bd3ca2b884
      path: 6tron/shields/zest_interface_ethernet
    - name: zest_interface_rs232
      repo-path: zephyr_zest-interface-rs232
      revision: 09def4139c923709e8ec2f3a68b9910d23619ae8
      path: 6tron/shields/zest_interface_rs232
    - name: zest_interface_rs485
      repo-path: zephyr_zest-interface-rs485
      revision: 316b980980d1b9ea91253aa528d559e15616f858
      path: 6tron/shields/zest_interface_rs485
    - name: zest_radio_gnss
      repo-path: zephyr_zest-radio-gnss
      revision: 74ab5c21ab63b11a4c569ea8f8356bcfa99055aa
      path: 6tron/shields/zest_radio_gnss
    - name: zest_radio_lora868
      repo-path: zephyr_zest-radio-lora868
      revision: e84a205b77c0742266ccc04f7097e0d24f7d8422
      path: 6tron/shields/zest_radio_lora868
    - name: zest_radio_wifi
      repo-path: zephyr_zest-radio-wifi
      revision: fbb419e254556548c096e18abab4a1f9ec5bb6f3
      path: 6tron/shields/zest_radio_wifi
    - name: zest_rtc_rv-8803-c7
      repo-path: zephyr_zest-rtc-rv-8803-c7
      revision: 6fa7a392f8dfed78e853e924be30eee4b2dfb504
      path: 6tron/shields/zest_rtc_rv-8803-c7
    - name: zest_sensor_imu
      repo-path: zephyr_zest-sensor-imu
      revision: 318a4f8d81fbfcd45a176c6a789599d429d941ba
      path: 6tron/shields/zest_sensor_imu
    - name: zest_sensor_p-t-rh
      repo-path: zephyr_zest-sensor-p-t-rh
      revision: cfd8ded7c0ba8fc20476c47115555d187d3d94d5
      path: 6tron/shields/zest_sensor_p-t-rh
    - name: zest_storage_microsd
      repo-path: zephyr_zest-storage-microsd
      revision: 406538f238c86e2f317e09554e64fc62f59d98e2
      path: 6tron/shields/zest_storage_microsd

    # ====================== Drivers =======================
    - name: ams_as621x
      repo-path: zephyr_ams-as621x
      revision: 096219be378848cb9a319b27095b5db6ce2f5fac
      path: 6tron/drivers/ams_as621x
    - name: bosch_bno055
      repo-path: zephyr_bosch-bno055
      revision: bbf91f02757d5155e99af76259dd89a0beada7ac
      path: 6tron/drivers/bosch_bno055
    - name: honeywell_hpma115
      repo-path: zephyr_honeywell-hpma115
      revision: 437d96964286d6022f8ec75d1f0c1ed6e036a170
      path: 6tron/drivers/honeywell_hpma115
    - name: ilitek_ili9163c
      repo-path: zephyr_ilitek-ili9163c
      revision: f9e99120884092e5604a15af8e03577bb9e5c79a
      path: 6tron/drivers/ilitek_ili9163c
    - name: maxim_max17201
      repo-path: zephyr_maxim-max17201
      revision: 67941660860215143ae021ad04c5c94de44b1e7e
      path: 6tron/drivers/maxim_max17201
    - name: microchip_mcp3425
      repo-path: zephyr_microchip-mcp3425
      revision: e8d169bf19acc563fe22ac45c753adaedf84ff87
      path: 6tron/drivers/microchip_mcp3425
    - name: microcrystal_rv8803
      repo-path: zephyr_microcrystal-rv8803
      revision: df67aea45b1ee6c1c60881f38b4882a96dbd472c
      path: 6tron/drivers/microcrystal_rv8803
    - name: omron_2smpb-02e
      repo-path: zephyr_omron-2smpb-02e
      revision: 28f602257de6b78a6f82fc826a4ba5c8aa9fcdc7
      path: 6tron/drivers/omron_2smpb-02e
    - name: quectel_l86
      repo-path: zephyr_quectel-l86
      revision: 96efc31c70890de20218fce76bbe26d4a603e05b
      path: 6tron/drivers/quectel_l86
    - name: sensirion_scd4x
      repo-path: zephyr_sensirion-scd4x
      revision: 3688d44c051071e721a08f4ce4ea8caa778eb62b
      path: 6tron/drivers/sensirion_scd4x
    - name: te-connectivity_htu21d
      repo-path: zephyr_te-connectivity-htu21d
      revision: cb10ac462907403ba2fcbc6289c80ecf59e1d302
      path: 6tron/drivers/te-connectivity_htu21d
    - name: ti_tsc2003
      repo-path: zephyr_ti-tsc2003
      revision: dc42e6145b39808a4dc5809db0f430c2648ec7ed
      path: 6tron/drivers/ti_tsc2003
